index:
  path: /
  controller: App\Controller\BlogController::index

verNoticia:
    path: /noticia/{id}
    controller: App\Controller\BlogController::verNoticia
    requirements:
        id: '\d+'

nuevaNoticia:
    path: /noticia/nueva
    controller: App\Controller\BlogController::nuevaNoticia

noticiaCreada:
    path: /noticia/creada
    controller: App\Controller\BlogController::noticiaCreada

noticiaEditar:
    path: /noticia/editar/{id}
    controller: App\Controller\BlogController::editarNoticia

noticiaBorrar:
    path: /apuesta/borrar/{id}
    controller: App\Controller\BlogController::borrarNoticia